### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by bntr00t** [carghai/rust_DDOS_attacker#3]
Using Arguments instead of simple input
ex: ./rust_ddos url mode proxy ai (new stuff for example a time for how long running, optional cookie argument, more info as to what AI mode does, syntax help(lolw), not using cargo run but cargo build in documentation

Having two modes:
1. Reading Proxies randomly from file(format ip:port)
2. Reading Proxy from Argument(singular proxy same format)

more customization of requests using randomisation against detections, rate limit etc

Overall this is really well made, works well and is nice to test my protection with against a new kind of client ^^

**Comment by carghai** [comment]
mmm that is very interesting i will work on  Reading Proxies randomly from file(format ip:port) this first

**Comment by carghai** [comment]
thanks btw I love the feedback!

**Comment by carghai** [comment]
Proxy mode done, header is done, just need documention

**Comment by carghai** [comment]
Done, thanks again for feedback!

**Comment by bntr00t** [comment]
> Proxy mode done, header is done, just need documention

Headers should rather be pre set
Proxies should be read from file via 

ip:port
ip:port

so by newline, as this is most used by proxy lists

**Comment by carghai** [comment]
i will do write by file soon, by next week

**Comment by carghai** [comment]
Due to unreliable behavior i will not do read by file. Sorry
