### ISSUE TITLE
start by args

### ISSUE THREAD

**Issue by bntr00t** [carghai/rust_DDOS_attacker#8]
./rust_ddos url udp proxy ai threads

remove headers from it and make them random from themselves, for example by reading them from a list(not file ik you dont like it)

**Comment by carghai** [comment]
Ok doing my research on this

**Comment by bntr00t** [comment]
use std::env;
let args: Vec<String> = env::args().collect();
let url = &args[1];
let udp = &args[2];
etc

^^

**Comment by carghai** [comment]
i released a test version rn in a different branch. It is not tested yet but when it is i will merge it to main.

**Comment by bntr00t** [comment]
Tested, there isnt yet any args reading, are you using some kind of if statement for this?

**Comment by carghai** [comment]
it reads it in headers set up were the user inputs header1|head_val1 etc

**Comment by carghai** [comment]
happy it work just need polish before being commited to main and released

**Comment by carghai** [comment]
tested and released. Thank again for helping me improve this tool!
